= Bathe-Booter

This artefact is designed for use with the Bathe Plugin or Spring Boot Loader (as the initial loading class).

As of Version 2.x, we use the Spring Boot Loader to manage classes, so the Bathe Booter becomes a simplier
set of behaviours:

* It will look in the +META-INF/MANIFEST.MF+ for the +Jump-Class+ (unless one is passed). It will jump
to the "run" or "main" method of this class passing the arguments once it has finished everything else.
* It will also look in the manifest for the for the +Implementation-Version+  as set in that manifest 
and sets it as a system property, allowing you to build versioned APIs and resources that reflect the 
application version (lmz-version uses this).
* It also provides you with an interface +BatheInitializer+ that allows you to create services that will run and
initialize before your main application runs simply by including them on the classpath. All your parameters are 
passed. We use this to set up the JUL loggers, load system properties, load secrets (passwords) from PWC's
secret server, start up Elastic and ensure it is running, etc.

Code is MIT license.
